# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

merge_columns_parallel <- function(index_matrix, x_sp_mat) {
    .Call('_SFE_merge_columns_parallel', PACKAGE = 'SFE', index_matrix, x_sp_mat)
}

calculate_count_shannon <- function(index_matrix, values_vector) {
    .Call('_SFE_calculate_count_shannon', PACKAGE = 'SFE', index_matrix, values_vector)
}

cal_shannon <- function(x) {
    .Call('_SFE_cal_shannon', PACKAGE = 'SFE', x)
}

